## Numpy basics

### 1 Numpy arrays

In [2]:
import numpy as np

In [3]:
mt = [5,10,20]

In [4]:
print(mt)

[5, 10, 20]


In [5]:
myarr = np.array(mt)

In [6]:
print(myarr)

[ 5 10 20]


In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_mtr = [[1,2,3] , [4,5,6], [7,8,9]]

In [9]:
np.array(my_mtr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
type(np.linspace(0,2,10))

numpy.ndarray

In [22]:
np.random.rand(5,5)

array([[0.09725626, 0.95935134, 0.39025183, 0.43269681, 0.12053438],
       [0.9731765 , 0.11296455, 0.19699348, 0.66720147, 0.25574724],
       [0.99416649, 0.89344746, 0.15738669, 0.29753824, 0.86760201],
       [0.89880957, 0.796331  , 0.85799748, 0.52040096, 0.596561  ],
       [0.88206   , 0.33211741, 0.93204887, 0.85040139, 0.36155053]])

In [24]:
np.random.randn(2,5)

array([[ 0.62041661, -1.07851232,  0.40156218, -1.07646409,  1.11212399],
       [-0.0559792 ,  0.06659399, -0.01069237, -2.9945456 ,  0.7283859 ]])

In [26]:
np.random.randint(0,110,5)

array([79, 72, 95,  7,  2])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [52]:
arr = np.arange(0,25)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr = np.random.randint(0,101,10)

In [34]:
ranarr

array([14, 44, 64, 88, 70,  8, 87,  0,  7, 87])

In [36]:
ranarr.max()

88

In [37]:
ranarr.min()

0

In [38]:
ranarr.argmax()

3

In [39]:
ranarr.argmin()

7

In [41]:
ranarr.dtype

dtype('int32')

In [55]:
arr.shape

(25,)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
arr = arr.reshape(5,5)

In [58]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
arr = arr.reshape(25,1)

In [60]:
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])