## Numpy indexing and selection

In [3]:
import numpy as np

In [9]:
arr = np.arange(5,20)

In [10]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
arr[6]

11

In [12]:
arr[1:5]

array([6, 7, 8, 9])

In [15]:
arr[:5]

array([5, 6, 7, 8, 9])

In [16]:
arr[:5]

array([5, 6, 7, 8, 9])

In [17]:
arr[:5] = 100

In [18]:
arr

array([100, 100, 100, 100, 100,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19])

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[-1]

10

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
slice_arr = arr[:5]

In [14]:
slice_arr

array([100, 100, 100, 100, 100])

In [15]:
arr_2d = np.array([[5,10,15], [20, 25,30], [35,40,45]])

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d.shape

(3, 3)

In [18]:
arr_2d[1]

array([20, 25, 30])

In [21]:
arr_2d[1,1]

25

In [23]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [24]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr = np.arange(0,20)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
arr>10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [33]:
bool_arr = arr>10

In [30]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [34]:
con_arr = arr[arr>10]

In [36]:
con_arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])